### ISSUE TITLE
S3ResponseError

### ISSUE THREAD

**Issue by a33151** [mishudark/s3-parallel-put#50]
hello，I use s3-parallel-put and getting a trouble 

python s3-parallel-put  --bucket=reocar-test --host=192.168.0.191:7480 --log-filename=/tmp/s3pp.log --dry-run --limit=1 .
Traceback (most recent call last):
  File "s3-parallel-put", line 459, in <module>
    sys.exit(main(sys.argv))
  File "s3-parallel-put", line 430, in main
    bucket = connection.get_bucket(options.bucket)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 509, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 542, in head_bucket
    raise err
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden

but i have  this bucket and my bucket can upload file or down 
I have been set access-key and secret-key in environment .

root@ceph1:~/s3-parallel-put-master# s3cmd ls
2018-08-02 05:46  s3://reocar-test

when i used 

python s3-parallel-put  --bucket=s3://reocar-test --host=192.168.0.191:7480 --log-filename=/tmp/s3pp.log --dry-run --limit=1 .

Traceback (most recent call last):
  File "s3-parallel-put", line 459, in <module>
    sys.exit(main(sys.argv))
  File "s3-parallel-put", line 430, in main
    bucket = connection.get_bucket(options.bucket)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 509, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 556, in head_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request

my host is ceph rgw s3  not   Amazon AWS S3

Did i miss some thing ? Thankyou !

**Comment by iCHAIT** [comment]
HI, 

Try using the following - 

```shell
python s3-parallel-put --bucket="reocar-test" --host=192.168.0.191:7480 --log-filename="/tmp/s3pp.log" --dry-run --limit=1 .
```

Note the double quotes for the `bucket` and the `log-filename` switches.

**Comment by a33151** [comment]
@iCHAIT 
Thank you! I sloved it.
